
// const PORT_NUMBER = 38321
// const JWT_SECRET = 'JhMRK4mRFWjV2mgoxaVK'
// const PORT_NUMBER_SOCKET = 41471
const KEYNAME_APIKEY = 'X_MBX_APIKEY' 

module.exports={
	// PORT_NUMBER ,
	// JWT_SECRET ,
	// PORT_NUMBER_SOCKET ,
	KEYNAME_APIKEY
}
