const KEYNAMES = {
  REDIS : {
    APIKEY : 'APIKEY' ,
    ASSETS : 'ASSETS' ,
    TRADEPAIRS : 'TRADEPAIRS' ,
    REF_STRIKEPRICE : 'REF_STRIKEPRICE' ,
    REF_MIDPRICE : 'REF_MIDPRICE' ,
    REF_MEAN_ORDER_AMOUNT : 'REF_MEAN_ORDER_AMOUNT' ,
    REF_VOLUME : 'REF_VOLUME' ,
    CHANNEL_NAME_COMMON : 'EX_CHANNEL_COMMON' , 
    RECEIVERS : {
      CHARGER : 'CHARGER' ,
      MARKETMAKER : 'MARKETMAKER' ,
      SYNCER : 'SYNCER' ,
      DRIFTER : 'DRIFTER' ,
    } ,
    ACTIONS : {
      RESTART : 'RESTART' ,
      START : 'START' ,
    }
    // MESSAGE_TYPE_CH ARGER : 'SIGNAL_CHA RGER' ,
  }
}
module.exports ={
  KEYNAMES
}
