const KEYNAMES = {
  REDIS : {
    APIKEY : 'APIKEY' ,
    ASSETS : 'ASSETS' ,
    TRADEPAIRS : 'TRADEPAIRS' ,
    REF_STRIKEPRICE : 'REF_STRIKEPRICE' ,
    REF_MIDPRICE : 'REF_MIDPRICE' ,
    REF_MEAN_ORDER_AMOUNT : 'REF_MEAN_ORDER_AMOUNT'
  }
}
module.exports ={
  KEYNAMES
}
